name: Tag version and major version

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: number
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: number
        
jobs: 
  tag-version:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Create Tag
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ inputs.version }}',
              sha: context.sha
          })
    - name: Update major version tag
      uses: actions/github-script@v7
      with:
        script: |
          const MAJOR = `${version}`.substring(0, version.indexOf("."))
          github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ MAJOR }}',
              sha: context.sha
          })
