name: Tag version and major version

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: number
      prefix:
        required: false
        type: string
        default: 'v'
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        default: 'v1.0.0'
        
jobs: 
  tag-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Create Tag
      uses: actions/github-script@v7
      with:
        script: |
          const version = "${{ inputs.version }}"
          const prefix = "${{ inputs.prefix }}"
          console.log(version)
          const prefixRe = new RegExp(`\\b^${prefix}\\b`)
          const major = `${version}`.replace(prefixRe, "").substring(0, version.indexOf("."))
          console.log(major)
          const tagParams = {
               owner: context.repo.owner,
               repo: context.repo.repo,
               ref: `tags/${ version }`,
          }
          console.log(tagParams)
          const { data: {object: {sha} } } = await github.rest.git.getRef(tagParams)
          console.log(sha)
          let majorTag
          // create major version tag
          const createRefParams = {
            ...context.repo,
            ref: `refs/tags/${prefix}${major}`,
            sha
          }
          console.log("createRefParams", createRefParams)
          majorTag = await github.rest.git.createRef(createRefParams)
          console.log(majorTag)
    # - name: Update major version tag
    #   uses: actions/github-script@v7
    #   with:
    #     script: |
    #       const core = require('@actions/core');
    #       const version = core.getInput('version')
    #       const major = `${version}`.substring(0, version.indexOf("."))
    #       github.rest.git.createRef({
    #           owner: context.repo.owner,
    #           repo: context.repo.repo,
    #           ref: 'refs/tags/v${{ major }}',
    #           sha: context.sha
    #       })
